### ISSUE TITLE
无法运行提示：ModuleNotFoundError: No module named 'answerrot'

### ISSUE THREAD

**Issue by CrazyEig** [anhkgg/answerot#2]

**Comment by anhkgg** [comment]
可否提供输入命令目录截图等

猜测应该是你运行目录不对

**Comment by CrazyEig** [comment]
图片发布出来我就把cmd发过来吧：
C:\Users\x>cd C:\Users\x\Desktop\answerot-master

C:\Users\x\Desktop\answerot-master>python manage.py runserver 0.0.0.0:8000
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x0000013910AE3400>
Traceback (most recent call last):
  File "C:\Python\Python36\lib\site-packages\django\utils\autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "C:\Python\Python36\lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "C:\Python\Python36\lib\site-packages\django\core\management\base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Python\Python36\lib\site-packages\django\core\management\base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Python\Python36\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Python\Python36\lib\site-packages\django\core\checks\urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "C:\Python\Python36\lib\site-packages\django\core\checks\urls.py", line 26, in check_resolver
    return check_method()
  File "C:\Python\Python36\lib\site-packages\django\urls\resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "C:\Python\Python36\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python\Python36\lib\site-packages\django\urls\resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python\Python36\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python\Python36\lib\site-packages\django\urls\resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\x\Desktop\answerot-master\answerot\urls.py", line 18, in <module>
    from server import views as server_views
  File "C:\Users\x\Desktop\answerot-master\server\views.py", line 7, in <module>
    import answerrot, adb
ModuleNotFoundError: No module named 'answerrot'

**Comment by anhkgg** [comment]
看提示是没有找到answerot-master\server\answerrot.py，麻烦确认是缺失该文件
如果有该文件，那再麻烦确认一下django版本和python版本，给出一下你的具体环境，我复现一下看看

**Comment by CrazyEig** [comment]
win10系统，文件answerrot.py存在，python -V显示Python 3.6.1，python -m django --version显示1.11.

**Comment by anhkgg** [comment]
那应该是python版本问题了，我是用的python2.7.14开发的，3以上版本python语法有些变化，我也没测过

你可以pyenv装一个py2.7的，或者直接降级成2.7也行，或者自己修改一下兼容3.6

**Comment by CrazyEig** [comment]
是的，我python换成2.7就没有报错了，谢谢你

**Comment by anhkgg** [comment]
ok，感谢使用

**Comment by CrazyEig** [comment]
不好意思，运行还是有点小问题提示没有网络。
![09q8m3z4o n0 l3 9zsez5h](https://user-images.githubusercontent.com/30516692/35390583-f353620e-0216-11e8-86c5-61f63c0ac2db.png)

**Comment by anhkgg** [comment]
401错误， [看这里](https://baike.baidu.com/item/401%E9%94%99%E8%AF%AF/3720974?fr=aladdin)

检查一下是否百度API应用的是否正确，是识字应用，填写正确的client_id和client_secret
